version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: magnum-db
    restart: always
    environment:
      MONGODB_DATABASE: magnum
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
