version: '3.8'

name: magnum

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magnum-app
    restart: always
    environment:
      GRPC_URL: 0.0.0.0:5000
    ports:
      - '3001:3000'
      - '5000:5000'
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
  db:
    image: mongo:latest
    container_name: magnum-db
    restart: always
    environment:
      MONGODB_DATABASE: magnum
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: magnum-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mongo_data:
    driver: local
