version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: magnum-db
    restart: always
    environment:
      MONGODB_DATABASE: magnum
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mongo_data:
    driver: local
