services:
  app:
    image: ghcr.io/mardudhq/magnum:latest
    container_name: magnum-app
    restart: always
    env_file:
      - ./app.env
    ports:
      - '3001:3000'
      - '5000:5000'
    depends_on:
      - db
      - rabbitmq

  db:
    image: mongo:latest
    container_name: magnum-db
    restart: always
    env_file:
      - ./db.env
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: magnum-rabbitmq
    restart: always
    env_file:
      - ./rabbitmq.env
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mongo_data:
    driver: local
